
export let timeDataTemp = [
	{
		id: "1720",
		creation_date: "",
		title: "The Battle for the Throne of 1720",
		image: "assets/placeholder.jpg",
		image_credit: "https://placeholder.com/",
		body: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec convallis, nisl ut maximus faucibus, nisi mi luctus mauris, ac auctor elit elit eu tortor. Sed aliquam sapien sed eros finibus feugiat. Sed elementum magna quis tortor tristique, at congue libero hendrerit. Duis rutrum ipsum eu enim ullamcorper, nec mattis orci efficitur. Nullam quis urna vel eros pretium suscipit. Sed viverra, nisi vel rutrum finibus, orci urna ullamcorper elit, non bibendum dolor elit euismod lacus. Praesent eget felis dui. Suspendisse ut nisl in nisi ornare vulputate. Praesent vel ipsum euismod, molestie quam a, auctor turpis.",
		start_date: "March 15, 1720",
	},
	{
		id: "1750",
		creation_date: "",
		title: "The Great War of 1750",
		image: "assets/placeholder.jpg",
		image_credit: "https://placeholder.com/",
		body: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec convallis, nisl ut maximus faucibus, nisi mi luctus mauris, ac auctor elit elit eu tortor. Sed aliquam sapien sed eros finibus feugiat. Sed elementum magna quis tortor tristique, at congue libero hendrerit. Duis rutrum ipsum eu enim ullamcorper, nec mattis orci efficitur. Nullam quis urna vel eros pretium suscipit. Sed viverra, nisi vel rutrum finibus, orci urna ullamcorper elit, non bibendum dolor elit euismod lacus. Praesent eget felis dui. Suspendisse ut nisl in nisi ornare vulputate. Praesent vel ipsum euismod, molestie quam a, auctor turpis.",
		start_date: "September 28, 1750",
	},
	{
		id: "1854",
		creation_date: "",
		title: "The Battle for Freedom of 1854",
		image: "assets/placeholder.jpg",
		image_credit: "https://placeholder.com/",
		body: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec convallis, nisl ut maximus faucibus, nisi mi luctus mauris, ac auctor elit elit eu tortor. Sed aliquam sapien sed eros finibus feugiat. Sed elementum magna quis tortor tristique, at congue libero hendrerit. Duis rutrum ipsum eu enim ullamcorper, nec mattis orci efficitur. Nullam quis urna vel eros pretium suscipit. Sed viverra, nisi vel rutrum finibus, orci urna ullamcorper elit, non bibendum dolor elit euismod lacus. Praesent eget felis dui. Suspendisse ut nisl in nisi ornare vulputate. Praesent vel ipsum euismod, molestie quam a, auctor turpis.",
		start_date: "June 2, 1854",
	},
	{
		id: "1855",
		creation_date: "",
		title: "The Battle for Independence of 1855",
		image: "assets/placeholder.jpg",
		image_credit: "https://placeholder.com/",
		body: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec convallis, nisl ut maximus faucibus, nisi mi luctus mauris, ac auctor elit elit eu tortor. Sed aliquam sapien sed eros finibus feugiat. Sed elementum magna quis tortor tristique, at congue libero hendrerit. Duis rutrum ipsum eu enim ullamcorper, nec mattis orci efficitur. Nullam quis urna vel eros pretium suscipit. Sed viverra, nisi vel rutrum finibus, orci urna ullamcorper elit, non bibendum dolor elit euismod lacus. Praesent eget felis dui. Suspendisse ut nisl in nisi ornare vulputate. Praesent vel ipsum euismod, molestie quam a, auctor turpis.",
		start_date: "December 11, 1855",
	},
	{
		id: "1860",
		creation_date: "",
		title: "The War for the Crown of 1860",
		image: "assets/placeholder.jpg",
		image_credit: "https://placeholder.com/",
		body: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec convallis, nisl ut maximus faucibus, nisi mi luctus mauris, ac auctor elit elit eu tortor. Sed aliquam sapien sed eros finibus feugiat. Sed elementum magna quis tortor tristique, at congue libero hendrerit. Duis rutrum ipsum eu enim ullamcorper, nec mattis orci efficitur. Nullam quis urna vel eros pretium suscipit. Sed viverra, nisi vel rutrum finibus, orci urna ullamcorper elit, non bibendum dolor elit euismod lacus. Praesent eget felis dui. Suspendisse ut nisl in nisi ornare vulputate. Praesent vel ipsum euismod, molestie quam a, auctor turpis.",
		start_date: "August 3, 1860",
	},
	{
		id: "1870",
		creation_date: "",
		title: "The Battle for Territory of 1870",
		image: "assets/placeholder.jpg",
		image_credit: "https://placeholder.com/",
		body: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec convallis, nisl ut maximus faucibus, nisi mi luctus mauris, ac auctor elit elit eu tortor. Sed aliquam sapien sed eros finibus feugiat. Sed elementum magna quis tortor tristique, at congue libero hendrerit. Duis rutrum ipsum eu enim ullamcorper, nec mattis orci efficitur. Nullam quis urna vel eros pretium suscipit. Sed viverra, nisi vel rutrum finibus, orci urna ullamcorper elit, non bibendum dolor elit euismod lacus. Praesent eget felis dui. Suspendisse ut nisl in nisi ornare vulputate. Praesent vel ipsum euismod, molestie quam a, auctor turpis.",
		start_date: "July 9, 1870",
	},
	{
		id: "1872",
		creation_date: "",
		title: "The Siege of the Capital of 1872",
		image: "assets/placeholder.jpg",
		image_credit: "https://placeholder.com/",
		body: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec convallis, nisl ut maximus faucibus, nisi mi luctus mauris, ac auctor elit elit eu tortor. Sed aliquam sapien sed eros finibus feugiat. Sed elementum magna quis tortor tristique, at congue libero hendrerit. Duis rutrum ipsum eu enim ullamcorper, nec mattis orci efficitur. Nullam quis urna vel eros pretium suscipit. Sed viverra, nisi vel rutrum finibus, orci urna ullamcorper elit, non bibendum dolor elit euismod lacus. Praesent eget felis dui. Suspendisse ut nisl in nisi ornare vulputate. Praesent vel ipsum euismod, molestie quam a, auctor turpis.",
		start_date: "November 6, 1872",
	},
	{
		id: "1874",
		creation_date: "",
		title: "The Battle for Unity of 1874",
		image: "assets/placeholder.jpg",
		image_credit: "https://placeholder.com/",
		body: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec convallis, nisl ut maximus faucibus, nisi mi luctus mauris, ac auctor elit elit eu tortor. Sed aliquam sapien sed eros finibus feugiat. Sed elementum magna quis tortor tristique, at congue libero hendrerit. Duis rutrum ipsum eu enim ullamcorper, nec mattis orci efficitur. Nullam quis urna vel eros pretium suscipit. Sed viverra, nisi vel rutrum finibus, orci urna ullamcorper elit, non bibendum dolor elit euismod lacus. Praesent eget felis dui. Suspendisse ut nisl in nisi ornare vulputate. Praesent vel ipsum euismod, molestie quam a, auctor turpis.",
		start_date: "May 18, 1874",
	},
	{
		id: "1882",
		creation_date: "",
		title: "The War for Resources of 1882",
		image: "assets/placeholder.jpg",
		image_credit: "https://placeholder.com/",
		body: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec convallis, nisl ut maximus faucibus, nisi mi luctus mauris, ac auctor elit elit eu tortor. Sed aliquam sapien sed eros finibus feugiat. Sed elementum magna quis tortor tristique, at congue libero hendrerit. Duis rutrum ipsum eu enim ullamcorper, nec mattis orci efficitur. Nullam quis urna vel eros pretium suscipit. Sed viverra, nisi vel rutrum finibus, orci urna ullamcorper elit, non bibendum dolor elit euismod lacus. Praesent eget felis dui. Suspendisse ut nisl in nisi ornare vulputate. Praesent vel ipsum euismod, molestie quam a, auctor turpis.",
		start_date: "April 27, 1882",
	},
	{
		id: "1940",
		creation_date: "",
		title: "The World War of 1940",
		image: "assets/placeholder.jpg",
		image_credit: "https://placeholder.com/",
		body: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec convallis, nisl ut maximus faucibus, nisi mi luctus mauris, ac auctor elit elit eu tortor. Sed aliquam sapien sed eros finibus feugiat. Sed elementum magna quis tortor tristique, at congue libero hendrerit. Duis rutrum ipsum eu enim ullamcorper, nec mattis orci efficitur. Nullam quis urna vel eros pretium suscipit. Sed viverra, nisi vel rutrum finibus, orci urna ullamcorper elit, non bibendum dolor elit euismod lacus. Praesent eget felis dui. Suspendisse ut nisl in nisi ornare vulputate. Praesent vel ipsum euismod, molestie quam a, auctor turpis.",
		start_date: "November 29, 1940",
	},
	{
		id: "1946",
		creation_date: "",
		title: "The Cold War of 1946",
		image: "assets/placeholder.jpg",
		image_credit: "https://placeholder.com/",
		body: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec convallis, nisl ut maximus faucibus, nisi mi luctus mauris, ac auctor elit elit eu tortor. Sed aliquam sapien sed eros finibus feugiat. Sed elementum magna quis tortor tristique, at congue libero hendrerit. Duis rutrum ipsum eu enim ullamcorper, nec mattis orci efficitur. Nullam quis urna vel eros pretium suscipit. Sed viverra, nisi vel rutrum finibus, orci urna ullamcorper elit, non bibendum dolor elit euismod lacus. Praesent eget felis dui. Suspendisse ut nisl in nisi ornare vulputate. Praesent vel ipsum euismod, molestie quam a, auctor turpis.",
		start_date: "July 16, 1946",
	},
	{
		id: "1990",
		creation_date: "",
		title: "The War for Equality of 1990",
		image: "assets/placeholder.jpg",
		image_credit: "https://placeholder.com/",
		body: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec convallis, nisl ut maximus faucibus, nisi mi luctus mauris, ac auctor elit elit eu tortor. Sed aliquam sapien sed eros finibus feugiat. Sed elementum magna quis tortor tristique, at congue libero hendrerit. Duis rutrum ipsum eu enim ullamcorper, nec mattis orci efficitur. Nullam quis urna vel eros pretium suscipit. Sed viverra, nisi vel rutrum finibus, orci urna ullamcorper elit, non bibendum dolor elit euismod lacus. Praesent eget felis dui. Suspendisse ut nisl in nisi ornare vulputate. Praesent vel ipsum euismod, molestie quam a, auctor turpis.",
		start_date: "February 1, 1990",
	},
	{
		id: "2000",
		creation_date: "",
		title: "The War for Resources of 2000",
		image: "assets/placeholder.jpg",
		image_credit: "https://placeholder.com/",
		body: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec convallis, nisl ut maximus faucibus, nisi mi luctus mauris, ac auctor elit elit eu tortor. Sed aliquam sapien sed eros finibus feugiat. Sed elementum magna quis tortor tristique, at congue libero hendrerit. Duis rutrum ipsum eu enim ullamcorper, nec mattis orci efficitur. Nullam quis urna vel eros pretium suscipit. Sed viverra, nisi vel rutrum finibus, orci urna ullamcorper elit, non bibendum dolor elit euismod lacus. Praesent eget felis dui. Suspendisse ut nisl in nisi ornare vulputate. Praesent vel ipsum euismod, molestie quam a, auctor turpis.",
		start_date: "January 1, 2000",
	},
	{
		id: "2020",
		creation_date: "",
		title: "The Cyber War of 2020",
		image: "assets/placeholder.jpg",
		image_credit: "https://placeholder.com/",
		body: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec convallis, nisl ut maximus faucibus, nisi mi luctus mauris, ac auctor elit elit eu tortor. Sed aliquam sapien sed eros finibus feugiat. Sed elementum magna quis tortor tristique, at congue libero hendrerit. Duis rutrum ipsum eu enim ullamcorper, nec mattis orci efficitur. Nullam quis urna vel eros pretium suscipit. Sed viverra, nisi vel rutrum finibus, orci urna ullamcorper elit, non bibendum dolor elit euismod lacus. Praesent eget felis dui. Suspendisse ut nisl in nisi ornare vulputate. Praesent vel ipsum euismod, molestie quam a, auctor turpis.",
		start_date: "October 22, 2020",
	},
];